version: 2.1
# Use a package of configuration called an orb.

orbs:
  # Choose either one of the orbs below
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  create_infrastructure: 
        docker:
          - image: amazon/aws-cli
        steps:
          - checkout
          - run:
              name: Create Cloudformation Stack
              command: |
                aws cloudformation deploy \
                  --template-file template.yml \
                  --stack-name myStack \
                  --region us-east-1
          - run:
              command: |
                  aws cloudformation describe-stack-events --stack-name myStack     
workflows:
  my_workflow:
      jobs:
        - create_infrastructure
